baseURL = 'http://franfabrizio.dev/'
languageCode = 'en-us'
title = 'franfabrizio.dev'
theme = "m10c"

[params]
  author = "fran"
  description = "Tech Notes from my Homelab"
  avatar = "/laptop-wave.png"
  favicon = ""
