baseURL = 'http://franfabrizio.dev/'
languageCode = 'en-us'
title = 'franfabrizio.dev'
theme = "hugo-theme-m10c"

[params]
  author = "fran"
  description = "Tech Notes from my Homelab"
  avatar = "/laptop-wave.png"
  favicon = ""
  # Minimum word count to display the Table of Contents
  tocMinWordCount = 500

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"

[services]
  [services.disqus]
    shortname = 'franfabrizio-dev'
  [services.googleAnalytics]
    ID = 'G-8LBKY582ZV'